### PR TITLE
Run tests for different clients/adapters

### PR DESCRIPTION
**Pull request by Nyholm**
This will show us how changes to this repo effects different clients/adapters

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Interesting idea. We might want to run the tests with the lowest PHP version we support in the given packages.

**Comment by Nyholm** [comment]
Sure, does not really matter. 

I want to do changes to the integration tests and I want to immediacy want to see how it effects our clients.

**Comment by sagikazarmark** [comment]
Yeah, that's a perfect use case IMO. But backward compatibility is important (forward compatibility is almost impossible to break)

**Comment by Nyholm** [comment]
But isn't BC something each adapter/client should test?

**Comment by sagikazarmark** [comment]
I mean BC of tests: if we start using anonymus classes for instance, we won't notice the break until a build is ran for a client.

**Comment by sagikazarmark** [comment]
Awesome thing @Nyholm , thanks

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
