### PR TITLE
Fix PHPUnit6 issue

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #21 

Is this a good solution? Im not sure how else we could do it. Any input is appreciated.

### CODE REVIEW

**Comment by Nyholm** [comment]
I've updated the PR now. This will work. 

Adding `printerClass="Http\Client\Tests\ResultPrinter" to phpunit.xml.dist will make sure this is class is used.

**Comment by dbu** [comment]
should you add the thing about the custom result printer to the readme? and should we use it in the phpunit.xml.dist provided by this repo?

**Comment by Nyholm** [comment]
I do not know. It is not a new feature. It is just adapted for PHPUnit 6.

**Comment by dbu** [comment]
fair enough

**Comment by dbu** [comment]
though providing some setup documentation in the README would not hurt if somebody builds their own adapter, or for us when we start a new adapter.

**Pull request merged**
