### PR TITLE
chore: fix ci deprecations

### PR DESCRIPTION
**Pull request by Chris53897**

### CODE REVIEW

**Comment by dbu** [comment]
thanks for this upgrade.

seems we have not looked at this since the projects switched to semantic branch naming. but your change is still valid, will merge it. and then will update the ci files.

**Comment by Chris53897** [comment]
thanks. I just want to keep a quick try if i can migrate it to PHPUnit 10/11.
But it seems there is some work todo, to make ci pass.

**Comment by dbu** [comment]
yeah we first need to fix the builds. it seems mostly code rot, i solved the curl-client issues and started working on socket-client issues in https://github.com/php-http/socket-client/pull/72

if you have time to look into the buzz or guzzle5/6 failures that would be awesome :-)

**Comment by Chris53897** [comment]
As this repos are readonly and archived. What todo?

**Comment by dbu** [comment]
the other maintainers on php-http have mostly moved to other things. and i also don't have very much time to invest. there is indeed quite some code rot.

i realized we archived guzzle5 and 6 adapter, so i removed them from the test. and buzz mostly succeeds now, there are just a few failures that seem to be on buzz side and not with the test setup, so i just merged #59, don't think we should invest more energy into it.

**Comment by dbu** [comment]
and thanks for the help - i appreciate it.

**Pull request merged**
