### PR TITLE
Support PHPUnit 8

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Nyholm** [comment]
The tests suggests that we need to release this as 3.0

**Comment by dbu** [comment]
yeah i fear we need it to be 3.0, the strict typehints will be hard errors if somebody overwrites one of those methods in a test.

**Comment by GrahamCampbell** [comment]
What's the status here. Also, could we add PHPUnit 9 support soon too?

**Comment by gmponos** [comment]
friendly ping.. can we add phpunit 9 as well here?

**Comment by GrahamCampbell** [comment]
Indeed, with PHP 9, we can also allow php 8 in the php version constraint.

**Pull request merged**
